// Vue-project-portfolio-1/src/components/MobileItu.vue
<template>
  <div class="mobile-itu">
    <div class="frame-183">
      <p class="at-international-tec ibmplexsans-normal-white-14px">
        <span class="ibmplexsans-normal-white-14px"
          >At International Technological University (ITU), I bridged the gap between user experience (UX) design and
          full-stack development, spearheading improvements across various platforms.<br />Elevating User Experience
          (UX): I identified crucial areas for improvement within the ITU website, Education Management System (EMS),
          and my.ITU.edu. By focusing on UX, I enhanced information architecture, navigation, and data visualization.
          These optimizations significantly improved accessibility and information clarity, positioning ITU as a leader
          in providing detailed information for prospective students.<br />Full-Stack Expertise &amp; User Interface
          (UI) Design: I leveraged my full-stack development skills and strong front-end expertise to enhance student
          and staff support. This included building user-friendly interfaces (UI) for various applications, prioritizing
          usability and accessibility for a seamless user journey.<br />Beyond Technical Skills:&nbsp;&nbsp;I
          demonstrated initiative and trust by providing valuable IT assistance to University President Yau.
          Additionally, my leadership skills were highlighted during my tenure as President of the Student Government
          Association (SGA).<br />Technical Acumen: Rounding out my skillset, I possess experience in deploying and
          maintaining applications on AWS cloud environments using automation tools. This showcases my ability to manage
          IT infrastructure effectively.<br /><br /></span
        ><span class="span1">{{ spanText2 }}</span
        ><span class="ibmplexsans-normal-white-14px">{{ spanText3 }}</span>
      </p>
    </div>
    <group103 />
  </div>
</template>

<script>
import Group103 from "./Group103";
export default {
  name: "MobileItu",
  components: {
    Group103,
  },
  props: ["spanText2", "spanText3"],
};
</script>

<style>
.mobile-itu {
  align-items: center;
  display: flex;
  gap: 15px;
  height: 510px;
  justify-content: flex-end;
  left: 0;
  min-width: 350px;
  padding: 47px 14px;
  position: absolute;
  top: 0;
}

.frame-183 {
  align-items: center;
  align-self: flex-end;
  display: flex;
  height: 415px;
  width: 289px;
}

.at-international-tec {
  height: 416px;
  letter-spacing: 0;
  line-height: 18px;
  margin-top: -1px;
  text-align: center;
  width: 289px;
}

.span1 {
  color: var(--white);
  font-family: var(--font-family-ibm_plex_sans);
  font-size: var(--font-size-xxs);
  font-weight: 700;
}
</style>

// React-project-portfolio-1/src/components/MobileItu/MobileItu.jsx
/*
We're constantly improving the code you see. 
Please share your feedback here: https://form.asana.com/?k=uvp-HPgd3_hyoXRBw1IcNg&d=1152665201300829
*/

import PropTypes from "prop-types";
import React from "react";
import "./style.css";

export const MobileItu = ({ property1, className }) => {
  return (
    <div className={`mobile-itu ${property1} ${className}`}>
      <div className="at-international-wrapper">
        <div className="at-international">
          <span className="text-wrapper">
            At International Technological University (ITU), I bridged the gap
            between user experience (UX) design and full-stack development,
            spearheading improvements across various platforms.
            <br />
            Elevating User Experience (UX): I identified crucial areas for
            improvement within the ITU website, Education Management System
            (EMS), and my.ITU.edu. By focusing on UX, I enhanced information
            architecture, navigation, and data visualization. These
            optimizations significantly improved accessibility and information
            clarity, positioning ITU as a leader in providing detailed
            information for prospective students.
            <br />
            Full-Stack Expertise &amp; User Interface (UI) Design: I leveraged
            my full-stack development skills and strong front-end expertise to
            enhance student and staff support. This included building
            user-friendly interfaces (UI) for various applications, prioritizing
            usability and accessibility for a seamless user journey.
            <br />
            Beyond Technical Skills:&nbsp;&nbsp;I demonstrated initiative and
            trust by providing valuable IT assistance to University President
            Yau. Additionally, my leadership skills were highlighted during my
            tenure as President of the Student Government Association (SGA).
            <br />
            Technical Acumen: Rounding out my skillset, I possess experience in
            deploying and maintaining applications on AWS cloud environments
            using automation tools. This showcases my ability to manage IT
            infrastructure effectively.
            <br />
            <br />
          </span>

          <span className="span">
            {property1 === "default" && (
              <>
                Key Takeaways:
                <br />
              </>
            )}

            {property1 === "variant-2" && (
              <>
                &nbsp;&nbsp;&nbsp;&nbsp; Key Takeaways:
                <br />
              </>
            )}
          </span>

          <span className="text-wrapper">
            Improved UX for critical university platforms
            <br />
            Designed user-friendly UIs for student &amp; staff applications
            <br />
            Demonstrated leadership &amp; communication skills
            <br />
            Possess strong cloud infrastructure management capabilities
          </span>
        </div>
      </div>

      <div className="group">
        <div className="overlap-group">
          <div className="rectangle" />
        </div>
      </div>
    </div>
  );
};

MobileItu.propTypes = {
  property1: PropTypes.oneOf(["variant-2", "default"]),
};
